language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
deploy:
  provider: surge
  project: ./build/
  skip_cleanup: true
  domain: halo.surge.sh
